version: '2'
services:
    web:
        build: .
        ports:
        - "80:80"
        volumes:
        - ./app:/var/www/apache-flask/app/
        restart: always
    redis:
        image: "redis:latest"
        entrypoint: redis-server --appendonly yes
        ports:
        - "6379:6379"
        volumes:
        - ./data:/data
        restart: always