version: '2'
services:
    web:
        build: .
        ports:
        - "80:80"
        volumes:
        - ./app:/var/www/apache-flask/app/
        restart: always
    redis:
        image: "redis:alpine"
        ports:
        - "6379:6379"
        restart: always